### ISSUE TITLE
Search Courses

### ISSUE THREAD

**Issue by scottpchow23** [ucsb-cs156-f20/ucsb-courses-search#5]
# User Story

As a user, I can enter a quarter, department, and a course level, and see a list of courses.

The information presented might be somewhat less, in the initial version, than what is available on https://my.sa.ucsb.edu/public/curriculum/coursesearch.aspx   so that we can leave some work for the students to do.

# Acceptance Criteria

- [ ] There is a method that can be called that queries the UCSB curriculum api for a list of departments.
- [ ] There are instructions in the README for configuration of the api key
- [ ] There is an application specific configuration property for start quarter and end quarter.
- [ ] On the main page of the app, there is a dropdown for quarter, a dropdown for department, and a drop down for course level.
- [ ] The dropdown for department is populated from the query to the UCSB Curriculum API
- [ ] The dropdown for quarter is populated from the start and end quarter values
- [ ] The dropdown for level can be populated with hard coded values.
- [ ] There is a service that takes the values supplied by the react form, converts them into a query, queries the ucsb curriculum api, and returns to the results in JSON form to the front end.   That service should handle the paging and return all of the JSON results at once.  In initial version, it's ok if we hard code the page size of the request at 100 and assume that we will never get more than 100 results, but in a subsequent version we should fix that.
- [ ] There is a React component that displays results of a course search as the raw JSON.    Converting that component to display the course results in a more reasonable format is a SEPARATE STORY.

**Comment by pconrad** [comment]
This issue has been replaced by issues #14, #16, #17, #18, #19
